### ISSUE TITLE
Edit button does not work as expected

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#146]
I have tried editing a model via the "Edit" button on the model card, but it does not work as expected.
Specifically, I tried to update the rdf in this model https://bioimage.io/#/?id=10.5072%2Fzenodo.880273 with [rdf.zip](https://github.com/bioimage-io/bioimage.io/files/6815349/rdf.zip).

However, the rdf in the latest zenodo version is not updated.
Note that the change from
```yaml
config:
  deepimagej:
    postprocess:
      - spec: null
    preprocess:
      - kwargs: scale_linear.ijm
        spec: ij.IJ::runMacroFile
```
to
```yaml
config:
  deepimagej:
    prediction:
      postprocess:
        - spec: null
      preprocess:
        - kwargs: scale_linear.ijm
          spec: ij.IJ::runMacroFile
```
is not done.
