### ISSUE TITLE
model downloader does not update filenames in architecture for pytorch_state_dict

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/archive.bioimage.io#371]
Hello,

I've noticed that the model downloader fails to create a self-contained `.zip` file for models in `pytorch_state_dict` format. I've observed this with [impartial-shrimp](https://bioimage.io/#/?id=10.5281%2Fzenodo.5874741). While the zip file contains all files necessary to run, the containing `rdf.yaml` does not point to the downloaded files for the archictecture, and readme for some reason:

<details><summary><code>rdf.yaml</code> (abbreviated) for "impartial-shrimp":</summary>

```yaml
...
description: Neuron segmentation in EM, trained on the CREMI challenge data.
documentation: https://zenodo.org/api/records/5874742/files/documentation.md/content
format_version: 0.4.5
...
weights:
  pytorch_state_dict:
    architecture: >-
      https://zenodo.org/api/records/5874742/files/unet.py/content:AnisotropicUNet
    architecture_sha256: 7f5b15948e8e2c91f78dcff34fbf30af517073e91ba487f3edb982b948d099b3
    kwargs:
      anisotropic_kernel: false
      final_activation: Sigmoid
      gain: 2
      in_channels: 1
      initial_features: 32
      out_channels: 1
      postprocessing: null
      return_side_outputs: false
      scale_factors:
        - - 1
          - 3
          - 3
        - - 1
          - 3
          - 3
        - - 2
          - 2
          - 2
        - - 2
          - 2
          - 2
        - - 2
          - 2
          - 2
    sha256: 9123de8cd1b9e7d4eaef56cb9d780a4dcbcfdf4b33f85559f6f392eeb06f6920
    source: ./weights.pt
```

</details>

I think the zip file should be self contained - and while it does not contain the markdown for the documentation, it does contain the architecture file and should point to it locally, not to zenodo.
